### ISSUE TITLE
Comptability issues with tModLoader v2024.5.3.3

### ISSUE THREAD

**Issue by nathruby** [Spiky-73/SpysInfiniteConsumables#15]
The issue I observed seemed to be in a recent update to the tMod Loader. Observed an issue where the objects are incompatible.

![image](https://github.com/user-attachments/assets/fb9cc8fa-f438-4eee-8c44-0c8cff19d1a8)

**Comment by nathruby** [comment]
Looking at the update. Seems to be with a recent update with the Library being updated and not TMod Loader.

I tried uninstalling the mod and the library and installing both again through the workshop, but I still have the same error.

**Comment by Spiky-73** [comment]
Can you send your json config files (`SPIC_InfinityDisplay.json` and `SPIC_InfinitySettings.json` in the ModConfig folder)?
I made some changes in the way some settings were serialized in the last Spiky's Lib update and I think it's not parsing them correctly.

**Comment by Spiky-73** [comment]
It is fixed in Spiky's Lib [v1.1.0.1](https://github.com/Spiky-73/SpikysLib/releases/tag/v1.1.0.1)

**Comment by nathruby** [comment]
Thank you for this! Saw the fix! Would the configs still help you for the future?

Also, I appreciate your work. Hard to find a mod out there that is just for infinite building or consumables!

**Comment by Spiky-73** [comment]
I don't think the configs will help anymore as the bug should be fixed. It would have been a way for me to easily reproduce the mod but I was able to do so with to screenshot you provided.
Thank you for the kind comment!
